export enum MoviesActions {
  GET_MOVIES = "GET_MOVIES",
  GET_MOVIES_SUCCESS = "GET_MOVIE_SUCCESS",
  CREATE_MOVIE = "CREATE_MOVIE",
  CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS",
  GET_MOVIE = "GET_MOVIE",
  GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS",
  UPDATE_MOVIE = "UPDATE_MOVIE",
  UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCC",
  DELETE_MOVIE = "DELETE_MOVIE",
  DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS",
}
